# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i 
    - run: npm run build
    - run: npm test
    # 部署到云服务器
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
        SSH_PRIVATE_KEY: ${{ secrets.TOKEN }} 
        # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
        # ARGS: "-avzr --delete" 
        # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
        SOURCE: "dist/" 
        # 服务器域名
        REMOTE_HOST: "47.100.116.130" 
        # 腾讯云默认用户名为root
        REMOTE_USER: "root" 
        # 目标目录
        TARGET: "/var/www/app"
